FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN install_packages \
        build-essential \
        ca-certificates \
        python-dev \
        python-pip-whl \
        python-pip \
        libffi-dev \
        libssl-dev \
        whois

# Install Python requirements
RUN pip install
    flask==1.0.2 \
    gevent-websocket==0.10.1 \
    gevent==1.2.2 \
    pyzmq==16.0.2 --no-cache-dir

COPY . /tmp/screenly

CMD ["bash", "/tmp/screenly/bin/start_balena.sh"]
