FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN apt-get update && apt-get install -y redis-server \
	&& apt-get clean && rm -rf /var/lib/apt/*

# initramfs compress as xz and modules as dep
COPY tests/config/initramfs.conf /etc/initramfs-tools/initramfs.conf

# clean up unnecessary disk space
COPY ansible/roles/system/files/01_nodoc /etc/dpkg/dpkg.cfg.d/

#CMD ["redis-server"]
CMD ["redis-server --protected-mode no"]
